import React, { useContext, useEffect, useRef, useState } from "react";
import { Container, Row, Button } from "reactstrap";
import { NavLink, Link } from "react-router-dom";

import logo from "../../assets/images/logo.png";
import "./header.css";
import { AuthContext } from "../../context/AuthContext";

const Header = () => {
  const [isMobileMenuOpen, setIsMobileMenuOpen] = useState(false);
  const { user } = useContext(AuthContext);
  const toggleMobileMenu = () => {
    setIsMobileMenuOpen(!isMobileMenuOpen);
  };

  const headerRef = useRef(null);

  const stickyHeaderFunc = () => {
    window.addEventListener("scroll", () => {
      if (
        document.body.scrollTop > 80 ||
        document.documentElement.scrollTop > 80
      ) {
        headerRef.current.classList.add("sticky__header");
      } else {
        headerRef.current.classList.remove("sticky__header");
      }
    });
  };

  useEffect(() => {
    stickyHeaderFunc();
    return window.removeEventListener("scroll", stickyHeaderFunc);
  });

  const nav__links = [
    {
      path: "/home",
      display: "Home",
    },
    {
      path: "/about",
      display: "About",
    },
    {
      path: "/tours",
      display: "Tours",
    },
  ];
  return (
    <header className="header" ref={headerRef}>
      <Container>
        <Row>
          <div className="nav__wrapper | d-flex align-items-center justify-content-between gap-sm-2 gap-md-4">
            {/* ============= logo ============= */}

            <div className="logo">
              <img src={logo} alt="" />
            </div>

            {/* ============== Logo End =========*/}

            {/* ============= Menu Start ============ */}
            <div className="navigation | d-none d-md-block">
              <ul className="menu | d-flex align-items-center gap-5">
                {nav__links.map((item, index) => (
                  <li className="nav_item" key={index}>
                    {/* navclass represent the css class generated by Navlink class and it has property of isActive */}
                    <NavLink
                      to={item.path}
                      className={(navClass) =>
                        navClass.isActive ? "active__link" : ""
                      }
                    >
                      {item.display}
                    </NavLink>
                  </li>
                ))}
              </ul>
            </div>
            {/* ============= Menu End ============ */}

            <div className="nav_right | d-none d-md-flex align-items-center gap-4">
              <div className="nav_btns | d-flex align-items-center gap-4">
                {user ? (
                  <span>Welcome, {user.userName}</span>
                ) : (
                  <>
                    <Button className="btn primary__btn">
                      <Link onClick={toggleMobileMenu} to="/login">
                        Login
                      </Link>
                    </Button>
                    <Button className="btn secondary__btn">
                      <Link onClick={toggleMobileMenu} to="/register">
                        Register
                      </Link>
                    </Button>
                  </>
                )}
              </div>
            </div>

            <div
              className="mobile__menu | d-block d-md-none"
              onClick={toggleMobileMenu}
            >
              <i className="ri-menu-line"></i>
            </div>
          </div>

          <div
            className={`mobile__navigation d-md-none ${
              isMobileMenuOpen ? "active" : ""
            }`}
          >
            <div className="mobile__menu-list | p-0 m-0 d-flex flex-column">
              {nav__links.map((item, index) => (
                <div className="mobile__nav_item | p-0 m-0" key={index}>
                  <NavLink
                    onClick={toggleMobileMenu}
                    to={item.path}
                    className={(navClass) =>
                      navClass.isActive ? "mobile__active__link" : ""
                    }
                  >
                    {item.display}
                  </NavLink>
                </div>
              ))}
              <div className="nav_btns | d-flex flex-column gap-4 my-4">
                {user ? (
                  <span>Welcome, {user.userName}</span>
                ) : (
                  <>
                    <Button className="btn primary__btn">
                      <Link onClick={toggleMobileMenu} to="/login">
                        Login
                      </Link>
                    </Button>
                    <Button className="btn secondary__btn">
                      <Link onClick={toggleMobileMenu} to="/register">
                        Register
                      </Link>
                    </Button>
                  </>
                )}
              </div>
            </div>
          </div>
        </Row>
      </Container>
    </header>
  );
};

export default Header;
